services:
  backend:
    build: ./backend
    container_name: portafolio_backend
    ports:
      - "8010:8010"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true

  frontend-es:
    build: ./frontend
    container_name: portafolio_frontend_es
    ports:
      - "4210:4210"
    volumes:
      - ./frontend:/app          # mantiene el bind mount de código fuente
      - /app/node_modules
    environment:
      - NG_CLI_ANALYTICS=false
      - NODE_OPTIONS=--max-old-space-size=1536
    depends_on:
      - backend
    command: npm run start:es
    stdin_open: true
    tty: true

  frontend-en:
    build: ./frontend
    container_name: portafolio_frontend_en
    ports:
      - "4211:4211"
    volumes:
      - ./frontend:/app          # mantiene el bind mount de código fuente
      - /app/node_modules
    environment:
      - NG_CLI_ANALYTICS=false
      - NODE_OPTIONS=--max-old-space-size=1536
    depends_on:
      - backend
    command: npm run start:en
    stdin_open: true
    tty: true
